<?php
/**
 * E-Way Bill Cancel API (CharteredInfo)
 *
 * POST body:
 * {
 *   "gstin": "33AAIFE9454A1ZN",
 *   "username": "earnestmin_API_buy",
 *   "authtoken": "19ZD...",
 *   "payload": {
 *     "ewbNo": "531958904356",
 *     "cancelRsnCode": "2",
 *     "cancelRmrk": "for testing"
 *   }
 * }
 */

header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, Authorization');
header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit;
}

require_once __DIR__ . '/../../../config/db.php';
require_once __DIR__ . '/../../../helpers/apiResponse.php';
require_once __DIR__ . '/../../../helpers/ewaybill.php';
require_once __DIR__ . '/../../../middleware/auth.php';

$user = AuthMiddleware::authenticate();

try {
    if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
        ApiResponse::error('Method not allowed', 405);
    }

    $input = json_decode(file_get_contents('php://input'), true);

    if (json_last_error() !== JSON_ERROR_NONE) {
        ApiResponse::error('Invalid JSON data');
    }

    $errors = [];
    foreach (['gstin', 'username', 'authtoken'] as $field) {
        if (!isset($input[$field]) || trim((string)$input[$field]) === '') {
            $errors[$field] = [strtoupper($field) . ' is required'];
        }
    }

    if (!isset($input['payload']) || !is_array($input['payload'])) {
        $errors['payload'] = ['Cancel payload is required'];
    } else {
        foreach (['ewbNo', 'cancelRsnCode', 'cancelRmrk'] as $field) {
            if (!isset($input['payload'][$field]) || trim((string)$input['payload'][$field]) === '') {
                $errors['payload_' . strtolower($field)] = [$field . ' is required'];
            }
        }
    }

    if (!empty($errors)) {
        ApiResponse::validationError($errors);
    }

    $gstinRaw = strtoupper(trim((string)$input['gstin']));
    $username = trim((string)$input['username']);
    $authToken = trim((string)$input['authtoken']);
    $ewbNoRaw = trim((string)$input['payload']['ewbNo']);

    if (strpos($gstinRaw, '{{') !== false || strpos($gstinRaw, '}}') !== false) {
        ApiResponse::validationError([
            'gstin' => ['GSTIN variable is unresolved. Select the correct Postman environment or provide raw GSTIN value.']
        ]);
    }

    if (!preg_match('/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[A-Z0-9]{1}Z[A-Z0-9]{1}$/', $gstinRaw)) {
        ApiResponse::validationError([
            'gstin' => ['Invalid GSTIN format. Expected 15-character GSTIN (example: 33AAIFE9454A1ZN).']
        ]);
    }

    if (strpos($username, '{{') !== false || strpos($username, '}}') !== false) {
        ApiResponse::validationError([
            'username' => ['Username variable is unresolved. Select the correct Postman environment or provide raw username.']
        ]);
    }

    if (strpos($authToken, '{{') !== false || strpos($authToken, '}}') !== false) {
        ApiResponse::validationError([
            'authtoken' => ['Auth token variable is unresolved. Run access-token API first or provide raw token.']
        ]);
    }

    if (strpos($ewbNoRaw, '{{') !== false || strpos($ewbNoRaw, '}}') !== false) {
        ApiResponse::validationError([
            'payload_ewbno' => ['EWB number variable is unresolved. Generate/fetch EWB first or provide raw ewbNo.']
        ]);
    }

    if (!preg_match('/^[0-9]{12}$/', $ewbNoRaw)) {
        ApiResponse::validationError([
            'payload_ewbno' => ['Invalid ewbNo format. Expected 12-digit E-Way Bill number.']
        ]);
    }

    $action = $input['action'] ?? 'CANEWB';
    $providerResult = EWayBillHelper::request(
        $action,
        [
            'aspid' => isset($input['aspid']) ? trim((string)$input['aspid']) : null,
            'password' => isset($input['password']) ? trim((string)$input['password']) : null,
            'gstin' => $gstinRaw,
            'username' => $username,
            'authtoken' => $authToken
        ],
        $input['payload'],
        $input['http_method'] ?? 'POST'
    );

    if (!$providerResult['success']) {
        $providerMessage = EWayBillHelper::providerMessage($providerResult['response']);
        $providerResponse = $providerResult['response'];
        if (is_string($providerResponse)) {
            $decodedResponse = json_decode($providerResponse, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $providerResponse = $decodedResponse;
            }
        }
        $providerCode = is_array($providerResponse)
            ? (string)($providerResponse['error']['error_cd'] ?? '')
            : '';

        if ($providerCode === '312') {
            $providerMessage = 'Provider 312: This E-Way Bill is either not generated by this GSTIN/username or already cancelled. Verify gstin, username, and ewbNo belong to same account.';
        }

        ApiResponse::error(
            $providerMessage,
            $providerResult['http_code'] > 0 ? $providerResult['http_code'] : 400,
            [
                'provider_response' => $providerResponse,
                'provider_url' => $providerResult['request_url']
            ]
        );
    }

    // Update ewaybill_log to reflect cancellation
    $pdo = getDBConnection();

    $cancelRsnCode = (string)($input['payload']['cancelRsnCode'] ?? '');
    $cancelRsnMap  = ['1' => 'Duplicate', '2' => 'Order Cancelled', '3' => 'Data Entry Mistake', '4' => 'Others'];
    $cancelReason  = ($cancelRsnMap[$cancelRsnCode] ?? 'Cancelled')
                     . (trim((string)($input['payload']['cancelRmrk'] ?? '')) !== ''
                        ? ' - ' . trim((string)$input['payload']['cancelRmrk'])
                        : '');

    $stmt = $pdo->prepare("
        UPDATE ewaybill_log
        SET status        = 'cancelled',
            cancel_date   = NOW(),
            cancel_reason = ?
        WHERE ewb_no = ?
    ");
    $stmt->execute([$cancelReason, $ewbNoRaw]);

    ApiResponse::success([
        'ewb_no'           => $ewbNoRaw,
        'status'           => 'cancelled',
        'cancel_reason'    => $cancelReason,
        'provider_response'=> $providerResult['response'],
        'provider_url'     => $providerResult['request_url']
    ], 'E-Way Bill cancelled successfully');
} catch (PDOException $e) {
    error_log('E-Way cancel API DB error: ' . $e->getMessage(), 3, __DIR__ . '/../../../logs/api_error.log');
    ApiResponse::serverError('Database error occurred');
} catch (Exception $e) {
    error_log('E-Way cancel API exception: ' . $e->getMessage(), 3, __DIR__ . '/../../../logs/api_error.log');
    ApiResponse::serverError($e->getMessage());
}
